title: AtomVM
email: info@atomvm.org
author: atomvm.org
description: >-
  Welcome to AtomVM, the Erlang virtual machine for IoT devices!
url: "https://atomvm.org"
github_username: atomvm
host: "atomvm.org"

markdown: kramdown

custom_favicon: "assets/images/favicon/favicon.ico"

plugins:
  - jekyll-feed

keep_files: [CNAME, .git, .nojekyll, doc]

sass:
  style: compressed
  sass_dir: _sass

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
